
# The following redirect is intended for use with most SPAs that handle
# routing internally.
[build]
  base = "frontend/"
  publish = "frontend/build"
  command = "yarn build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200